export type FoodAliasTier = 0 | 1 | 2 | 3 | 4;

// Food pool expanded from truanayangi.com (theme=tram-tiep-te).
// Rarity tiers: 0: QUỐC DÂN, 1: HIẾM, 2: CỰC PHẨM, 3: TỐI MẬT, 4: ★ ĐẶC BIỆT.
export const foodAliasesByTier = [
  [
    'Bánh mì',
    'Cơm chay',
    'Hủ tiếu',
    'Bún thịt nướng',
    'Bánh cuốn',
    'Bún cá',
    'Gỏi cuốn',
    'Cháo sườn',
    'Mì nấm chay',
    'Bánh mì chay',
    'Gỏi cuốn chay',
    'Cơm bình dân',
    'Bún chay',
    'Cháo lòng',
    'Bánh mì kebab',
    'Xôi mặn',
    'Trà chanh',
    'Trà tắc',
    'Nước mía',
    'Sữa đậu nành',
    'Nước sâm',
    'Hồng trà',
    'Trà xanh',
    'Nước rau má',
    'Nước chanh',
    'Nước chanh muối',
    'Sâm bí đao',
    'Nước lọc đóng chai',
    'Bánh flan',
    'Sữa chua nếp cẩm',
    'Bắp nướng mỡ hành',
    'Bắp luộc',
    'Khoai lang nướng',
    'Chuối chiên',
    'Bánh tiêu',
    'Bánh bò hấp',
    'Bánh da lợn',
    'Bánh chuối hấp',
    'Tào phớ',
    'Kem chuối',
    'Đậu phộng rang',
    'Hạt hướng dương',
    'Hạt bí rang',
    'Rong biển sấy',
    'Đậu nành rang',
    'Dưa hấu',
    'Ổi',
    'Cóc',
    'Cam',
    'Quýt',
    'Thanh long',
    'Chuối',
    'Dưa chuột',
    'Lạc rang',
    'Ngô chiên',
    'Gỏi xoài khô bò',
    'Rau muống xào tỏi',
    'Đậu hũ chiên sả',
    'Cà tím nướng mỡ hành',
    'Đậu bắp nướng',
  ],
  [
    'Cơm tấm',
    'Phở bò',
    'Bún chả',
    'Gà rán',
    'Cơm gà Hội An',
    'Bún bò Huế',
    'Mì Quảng',
    'Bún đậu mắm tôm',
    'Cơm rang dưa bò',
    'Bánh xèo',
    'Bánh đa cua',
    'Mì xào bò',
    'Tteokbokki',
    'Burger bò',
    'Cơm gà xối mỡ',
    'Bún riêu',
    'Bánh canh cua',
    'Phở gà',
    'Bún mọc',
    'Bún măng vịt',
    'Bún bò Nam Bộ',
    'Bún mắm',
    'Bánh canh giò heo',
    'Miến gà',
    'Miến lươn',
    'Cháo vịt',
    'Bánh hỏi heo quay',
    'Nem nướng',
    'Mì hoành thánh',
    'Mì cay Hàn Quốc',
    'Cơm chiên kimchi',
    'Nui xào bò',
    'Cháo gà',
    'Bò kho bánh mì',
    'Bánh mì chảo',
    'Cơm xá xíu',
    'Mì xá xíu',
    'Miến xào',
    'Cháo thịt nạc trứng bắc thảo',
    'Cà phê đen đá',
    'Cà phê sữa đá',
    'Bạc xỉu',
    'Trà sữa Thái',
    'Trà vải',
    'Nước ép cam',
    'Nước ép dưa hấu',
    'Nước ép dứa',
    'Nước ép ổi',
    'Nước dừa',
    'Cà phê muối',
    'Trà ô long',
    'Cacao sữa',
    'Nước ép cà rốt',
    'Nước ép cóc',
    'Sinh tố dưa gang',
    'Sữa hạt sen mè đen',
    'Sữa đậu xanh cốt dừa',
    'Sữa chua đá',
    'Rau má đậu xanh',
    'Nước mơ',
    'Nước sấu',
    'Nước chanh dây',
    'Soda chanh',
    'Soda dâu',
    'Soda việt quất',
    'Bánh tráng trộn',
    'Cá viên chiên',
    'Khoai tây chiên',
    'Chè đậu đen',
    'Bánh trứng nướng',
    'Bánh tráng nướng',
    'Bánh tráng cuốn',
    'Bánh tráng bơ',
    'Bánh gối',
    'Bánh rán mặn',
    'Bánh giò',
    'Bánh đúc nóng',
    'Bánh nậm',
    'Bánh khọt',
    'Bắp xào tôm khô',
    'Khoai lang kén',
    'Xúc xích nướng',
    'Trứng cút lộn xào me',
    'Khô gà lá chanh',
    'Mực rim me',
    'Bánh cam',
    'Bánh bò nướng',
    'Bánh khoai mì nướng',
    'Bánh su kem',
    'Chè bưởi',
    'Chè ba màu',
    'Chè đậu xanh',
    'Chè đậu đỏ',
    'Chè trôi nước',
    'Chè khoai dẻo',
    'Chè sương sa hạt lựu',
    'Sữa chua mít',
    'Kem xôi',
    'Bánh đúc lá dứa',
    'Hạt dẻ rang',
    'Dưa lưới',
    'Xoài chín',
    'Thơm (dứa)',
    'Bưởi',
    'Mít',
    'Chôm chôm',
    'Nhãn',
    'Vải',
    'Mãng cầu ta (na)',
    'Vú sữa',
    'Táo',
    'Roi (mận miền Nam)',
    'Đậu tẩm hành',
    'Ngọn su su xào tỏi',
    'Rau củ luộc chấm kho quẹt',
    'Cải thìa xào nấm',
    'Nộm xoài tép khô',
    'Nghêu hấp sả',
    'Hàu sữa nướng mỡ hành',
    'Ốc móng tay xào rau muống',
  ],
  [
    'Pizza',
    'Bibimbap',
    'Bò lúc lắc',
    'Ramen',
    'Udon',
    'Cơm cà ri Nhật',
    'Mì Ý bò bằm',
    'Pad Thai',
    'Mì Tom Yum',
    'Bò né',
    'Cơm gà teriyaki',
    'Cơm heo chiên xù',
    'Cơm chiên hải sản',
    'Mì vịt tiềm',
    'Kimbap',
    'Mì trộn Hàn Quốc',
    'Salad ức gà',
    'Phở cuốn',
    'Mì bò Đài Loan',
    'Mì xào giòn',
    'Cơm niêu Singapore',
    'Cơm gà Hải Nam',
    'Cơm gà trứng Nhật',
    'Mì tương đen',
    'Mì lạnh Hàn Quốc',
    'Canh kimchi kèm cơm',
    'Canh đậu hũ non kèm cơm',
    'Sandwich',
    'Bánh cuộn gà',
    'Cơm vịt quay',
    'Burger gà & khoai tây',
    'Cơm đậu hũ Mapo',
    'Cơm gà Kung Pao',
    'Cơm heo xào cay Jeyuk',
    'Cơm cuộn trứng Omurice',
    'Cơm heo xào gừng Shogayaki',
    'Cơm trà cá hồi Ochazuke',
    'Trà sữa trân châu',
    'Trà sữa ô long',
    'Trà đào cam sả',
    'Sinh tố bơ',
    'Sinh tố xoài',
    'Sinh tố chuối',
    'Espresso',
    'Trà sữa trà xanh',
    'Trà sữa khoai môn',
    'Trà sữa lài',
    'Trà nhãn sen',
    'Trà xoài',
    'Trà mãng cầu',
    'Nước ép táo',
    'Nước ép bưởi',
    'Sinh tố mãng cầu',
    'Sinh tố sapoche',
    'Sữa tươi trân châu đường đen',
    'Sữa chua việt quất',
    'Sữa chua chanh dây',
    'Nem chua rán',
    'Takoyaki',
    'Trái cây dầm',
    'Hạt điều rang',
    'Bột chiên',
    'Há cảo tôm',
    'Sủi cảo chiên',
    'Bánh bèo',
    'Bánh bột lọc',
    'Ốc luộc',
    'Khô bò sợi',
    'Bông lan trứng muối',
    'Chè Thái',
    'Kem dừa',
    'Đu đủ',
    'Măng cụt',
    'Sapoche',
    'Nho',
    'Tóp mỡ xào dưa',
    'Mực khô nướng xé',
    'Chân gà sốt Thái',
    'Lòng gà xào mướp',
    'Dồi sụn nướng',
    'Tai heo bóp thính',
    'Ốc len xào dừa',
    'Sò huyết xào me',
    'Tôm nướng muối ớt',
  ],
  [
    'Lẩu nấm chay',
    'Mì Ý sốt kem bacon',
    'Lasagna bò',
    'Burger bò phô mai & khoai tây',
    'Pizza pepperoni',
    'Cơm bò gyudon',
    'Cơm cá saba nướng',
    'Mì soba Nhật',
    'Cơm cà ri Thái',
    'Salad cá ngừ',
    'Salad quinoa đậu gà',
    'Dimsum',
    'Cơm tempura',
    'Gà phô mai Hàn Quốc',
    'Lẩu Thái một người',
    'Bánh xèo Nhật',
    'Mì udon xào',
    'Mì Kalguksu hải sản',
    'Cơm thịt băm Hambagu',
    'Masala dosa',
    'Matcha latte',
    'Sinh tố dâu',
    'Americano',
    'Cà phê ủ lạnh',
    'Cà phê trứng',
    'Cà phê cốt dừa',
    'Hojicha latte',
    'Matcha latte dâu',
    'Cacao kem muối',
    'Sô cô la đá xay',
    'Bánh quy kem đá xay',
    'Matcha đá xay',
    'Phô mai que',
    'Ốc xào dừa',
    'Sò điệp nướng mỡ hành',
    'Lòng xào dưa',
    'Sụn gà rang muối',
    'Má đào cháy tỏi',
    'Gà chiên mắm',
    'Sụn gà chiên mắm',
    'Ba chỉ rang riềng',
    'Ba chỉ nướng riềng mẻ',
    'Gân bò cháy tỏi',
    'Bò xào cần',
    'Ếch xào sả ớt',
    'Ếch chiên bơ',
    'Vịt cháy tỏi',
    'Lưỡi vịt rang muối',
    'Mực hấp gừng sả',
    'Mực trứng chiên lá lốt',
    'Râu mực chiên mắm',
  ],
  [
    'Sushi cá hồi',
    'Bò bít tết',
    'Cá hồi áp chảo',
    'Cơm lươn Nhật',
    'Cơm bò nướng Hàn',
    'Cơm cá hồi teriyaki',
    'Poke cá hồi',
    'Sườn nướng BBQ',
    'Pizza hải sản',
    'Mì Ý hải sản',
    'Lẩu bò cá nhân',
    'Lẩu sukiyaki một người',
    'Cà ri Ấn Độ & naan',
    'Cơm biryani',
    'Burrito',
    'Taco',
    'Quesadilla',
    'Fish & chips',
    'Gà nướng kèm khoai tây',
    'Mac & cheese',
    'Mì Ý pesto',
    'Mì Ý cá hồi',
    'Cơm risotto',
    'Gnocchi',
    'Falafel kèm pita',
    'Mì Ý sốt cà chua & phô mai',
    'Mì Dan Dan Tứ Xuyên',
    'Gà hầm sâm Samgyetang',
    'Canh sườn bò Galbitang kèm cơm',
    'Chole bhature',
    'Palak paneer kèm cơm',
    'Gà tandoori kèm naan',
    'Latte',
    'Cappuccino',
    'Bánh cheesecake',
    'Chân gà sả tắc',
    'Chân gà nướng',
    'Sầu riêng',
    'Dạ dày cháy tỏi',
    'Chim câu quay',
  ],
] as const satisfies readonly (readonly string[])[];

export function isFoodAliasForTier(value: string, tier: FoodAliasTier) {
  return (foodAliasesByTier[tier] as readonly string[]).includes(value);
}

function draw(random: () => number) {
  const value = random();
  if (!Number.isFinite(value) || value < 0 || value >= 1)
    throw new Error('Random draw must be in [0,1)');
  return value;
}

function shuffled<T>(items: readonly T[], random: () => number) {
  const result = [...items];
  for (let index = result.length - 1; index > 0; index--) {
    const swap = Math.floor(draw(random) * (index + 1));
    [result[index], result[swap]] = [result[swap]!, result[index]!];
  }
  return result;
}

export function createSeededRandom(seed: string) {
  let state = 2_166_136_261;
  for (const character of seed) {
    state ^= character.codePointAt(0)!;
    state = Math.imul(state, 16_777_619);
  }
  return () => {
    state = (state + 0x6d2b79f5) | 0;
    let value = state;
    value = Math.imul(value ^ (value >>> 15), value | 1);
    value ^= value + Math.imul(value ^ (value >>> 7), value | 61);
    return ((value ^ (value >>> 14)) >>> 0) / 4_294_967_296;
  };
}

export function assignFoodAliases<T extends { tier: FoodAliasTier }>(
  items: readonly T[],
  random: () => number,
): Array<T & { publicName: string }> {
  const names = new Array<string>(items.length);
  for (const tier of [0, 1, 2, 3, 4] as const) {
    const indexes = items.flatMap((item, index) =>
      item.tier === tier ? [index] : [],
    );
    const pool = foodAliasesByTier[tier];
    let aliases: string[] = [];
    let position = 0;
    for (const index of indexes) {
      if (position === aliases.length) {
        aliases = shuffled(pool, random);
        position = 0;
      }
      names[index] = aliases[position++]!;
    }
  }
  return items.map((item, index) => ({
    ...item,
    publicName: names[index]!,
  }));
}
